### ISSUE TITLE
Support passing features to Cargo

### ISSUE THREAD

**Issue by abonander** [rust-fuzz/honggfuzz-rs#12]
I created a bin target for using Honggfuzz with my library (reverted on master because of this issue and also because `cargo-fuzz` works on WSL now):

* https://github.com/abonander/mvp-tree-rs/blob/c1f57813fe61d2c20845bae92b441a2f64fd8513/Cargo.toml
* https://github.com/abonander/mvp-tree-rs/blob/1734fab76cba614f98ae173453971c736d584e3c/src/bin/honggfuzz_iter.rs

However, I cannot pass the `honggfuzz` feature to Cargo because the `cargo-hfuzz` executable doesn't support it.

**Comment by PaulGrandperrin** [comment]
Hi @abonander,
I'm not a big fan of how features work in cargo because of this exact situation but anyway, there is 2 solutions:
- you can pass the feature argument to `cargo build` with an env var like this
```
HFUZZ_BUILD_ARGS="--features=honggfuzz" cargo hfuzz run honggfuzz_iter
```
This is not very nice looking or intuitive but I'm planning to find a better solution in the next major version of the CLI.
- you can make the `honggfuzz` dependancy conditional on the `fuzz` cfg tag like so:
```
[target.'cfg(fuzzing)'.dependencies]
honggfuzz = { version = "0.5"}
```

Please don't hesitate to reopen if you have any questions or suggestions!
